### ISSUE TITLE
 上位バージョンでは動かない

### ISSUE THREAD

**Issue by y-arai** [matsukei/redmine_serial_number_field#1]
redmine 3.2.1を使用しているのですが、
指示の通りプラグインに入れても、動作されずREDMINE自体が起動しなくなりました。
プラグインを消すと正常に動作しています。

記載の通り上位バージョンが対応されていないのでしょうか。

お忙しいところお手数ですが確認お願いします。

**Comment by maeda-m** [comment]
@y-arai 

報告ありがとうございます。

Install に記載していた手順に漏れがありました。
以下のコマンドを実施後、Redmineを再起動してください。

```
$ cd your_redmine_path/
$ bundle install
```

**Comment by y-arai** [comment]
ありがとうございました。
無事動作しました。

BITNAMI版だったのでBitnami Redmine Stack でも
只のＩｎｓｔａｌｌではＮＧで下記コマンドが必要でした

cd apps/redmine/htdocs
bundle install --without development test postgresql sqlite
ruby bin/rake redmine:plugins RAILS_ENV=production

同様の方は参考までに記載しておきます。
