### ISSUE TITLE
連番フォーマットのみでは動作しない

### ISSUE THREAD

**Issue by y-arai** [matsukei/redmine_serial_number_field#2]
もう一つ確認お願いします。

ＯＫとなっている連番フォーマットのみ(例えば{000000})では
「正規表現 は不正な値です」
と表示してしまいます。

何かしら文字を付加すると問題ないのですが
(例えば-{000000}やa{000000}はＯＫ)
連番フォーマットのみは可能でしょうか。

**Comment by maeda-m** [comment]
Closed via f870d75a5bf6afd56c06ff20759e6b49903c1daf
