### ISSUE TITLE
The serial number counter will be reset for each project, instead of global counter

### ISSUE THREAD

**Issue by neocosmic2** [matsukei/redmine_serial_number_field#4]

**Comment by maeda-m** [comment]
Hi, @neocosmic2 

That behavior is correct. This plugin is serial number for each project.
Do you need a common serial number for all projects, like issue number?

**Comment by neocosmic2** [comment]
Yup, because SN number will be duplicated across each project

On 14 Jun 2017 08:15, "Minoru Maeda" <notifications@github.com> wrote:

Hi, @neocosmic2 <https://github.com/neocosmic2>

That behavior is correct. This plugin is serial number for each project.
Do you need a common serial number for all projects, like issue number?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matsukei/redmine_serial_number_field/issues/4#issuecomment-308283735>,
or mute the thread

**Comment by maeda-m** [comment]
I see. I will implement it in the next release.

Thank you.

**Comment by neocosmic2** [comment]
Thanks for your great effort

On 14 Jun 2017 08:46, "Minoru Maeda" <notifications@github.com> wrote:

I see. I will implement it in the next release.

Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matsukei/redmine_serial_number_field/issues/4#issuecomment-308287979>,
or mute the thread

**Comment by maeda-m** [comment]
Closed via 2ae7fa69c5e5e37ec91493e3ba13a3699e418503
