### ISSUE TITLE
チケットコピー時に自動採番されない

### ISSUE THREAD

**Issue by subaru019** [matsukei/redmine_serial_number_field#6]
チケットコピー時に自動採番されず、コピー元の番号が引き継がれます。
この動作は仕様でしょうか？
チケットコピー時も自動採番することを希望します。

**Comment by maeda-m** [comment]
@subaru019 報告ありがとうございます。

> この動作は仕様でしょうか？

改めて実装を見てみると、チケットコピーについては対応していませんでした（テストがない）。

> チケットコピー時も自動採番することを希望します。

そうですね。対応してみます。

**Comment by maeda-m** [comment]
www.redmine.org においても同じ様な質問があったため、記録する。

---

User ratings from http://www.redmine.org/plugins/redmine_serial_number_field

- by Jorge Garcia
> It is a good contribution, and I am using it in my company, but I would like it to be calculated when the request arrives at a certain state. for example, when the issue is in the new state is not shows the serial #, only when it reaches the next etate.

-  by Quan VN
> Fix the copy issue by edit file issue_patch.rb, line 15, change it into 
next if assigned_serial_number?(cf) && !copy?

- by qn wang
> A helpful plugin, thank you Maeda.But I found when COPY a issue, the Serial Number is not increased but the same as the oringinal one. would you try to fix it?

**Comment by maeda-m** [comment]
Closed via #11 , Thanks.
