### ISSUE TITLE
フォーマットのルールがわかりません。

### ISSUE THREAD

**Issue by yakkung** [matsukei/redmine_serial_number_field#9]
こちらでこのような質問をしてよいものかわからないまま、ほかの手段を見つけられず失礼します。
「正規表現」に「年」「月」「連番」を指定したく、{yy}{MM}{00} としてみましたが、「正規表現 に無効なフォーマットが含まれています。」とのこと。
年2桁が「yy」とのことなので月は「MM」もしくは「mm」で行けるかと思ったのですがだめでした。年月を指定できるフォーマットがあればご教示しただきたく。よろしくお願いします。

**Comment by maeda-m** [comment]
質問ありがとうございます。フォーマットは年と連番しかなく、月については未対応です。
https://github.com/matsukei/redmine_serial_number_field#format-specifications

**Comment by yakkung** [comment]
ファーマットないとのこと、残念ですが了解しました。
すばやい回答ありがとうございました。

**Comment by yakkung** [comment]
closeしときながら再度失礼します。
/lib/format.rb の DATE_FORMATS = { ～ } に、
`:'mm'`   => { :strftime => '%m', :financial_year => false, :regexp => MATCHERS[:TOW_DIGIT_NUMBER] }
を追加してみたところ採番されるようになりました。
月が替わると連番部分はちゃんとリセットされるようです。
この改造は許可いただけますでしょうか？

**Comment by maeda-m** [comment]
月も採番フォーマットに追加すると採番されたのですね。よかったです。
#8 のようにプルリクエストをもらえると助かります。
※ `:regexp => MATCHERS...` の部分がなぜ必要だったか思い出せないので #8 は手を止めています、、、

**Comment by yakkung** [comment]
たびたび失礼します。
11月にはいって採番がおかしい事に気づきました。
2019/11の1件目の場合、
{yy}{mm}{00}フォーマットで
191101 となって欲しいところ、
190101 となってしまいます。
今調査中ですが、取り急ぎ連絡まで。
安易な改造で大失敗してしまいました。申し訳ありません。

**Comment by yakkung** [comment]
フォーマットに追加するのを下記に変更しました。
:'yymm' => { :strftime => '%y%m', :financial_year => false, :regexp => MATCHERS[:FOUR_DIGIT_NUMBER] }
たびたび失礼しました。
ありがとうございます。
